const API = window.GEORUSH_API || "http://127.0.0.1:8000";
let LAST_CRAWL = null;
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));

async function api(path, options = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 15000);
  try {
    const response = await fetch(`${API}${path}`, {...options, signal: controller.signal});
    const text = await response.text();
    let data; try { data = JSON.parse(text); } catch { data = {detail:text}; }
    if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`);
    return data;
  } finally { clearTimeout(timer); }
}

const titles = {dashboard:"SEO Command Center",keywords:"Keywords",rankings:"Rankings",competitors:"Competitors",audit:"Site Audit",content:"Content",backlinks:"Backlinks",analytics:"Analytics"};
function showPage(page, updateHash=true) {
  if (!titles[page]) page="dashboard";
  $$('[data-section]').forEach(s => s.hidden = s.dataset.section !== page);
  $$('.nav-link').forEach(a => a.classList.toggle('active', a.dataset.page===page));
  if ($('#pageTitle')) $('#pageTitle').textContent=titles[page];
  if (updateHash && location.hash !== `#${page}`) history.replaceState(null,'',`#${page}`);
  renderModule(page);
  window.scrollTo({top:0,behavior:'smooth'});
}
function initNavigation(){
  $$('.nav-link').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();showPage(a.dataset.page);}));
  showPage(location.hash.replace('#','')||'dashboard',false);
  window.addEventListener('hashchange',()=>showPage(location.hash.replace('#',''),false));
}
async function checkAPI(){try{await api('/api/health');$('#apiStatus').textContent='API ONLINE';}catch{$('#apiStatus').textContent='API OFFLINE';}}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function rowHtml(x){return `<tr><td class="url">${escapeHtml(x.url)}</td><td>${x.status_code??''}</td><td>${escapeHtml(x.title||'—')}</td><td>${x.word_count??0}</td><td>${x.response_time_ms??0} ms</td><td>${escapeHtml((x.issues||[]).join(', ')||'None')}</td></tr>`;}
function renderResults(data){LAST_CRAWL=data; localStorage.setItem('GEORUSH_LAST_CRAWL',JSON.stringify(data));$('#score').textContent=data.seo_score?.total??'—';$('#pages').textContent=data.pages??0;$('#issues').textContent=data.issues??0;$('#status').textContent='COMPLETE';$('#rows').innerHTML=data.results?.length?data.results.map(rowHtml).join(''):'<tr><td colspan="6">No crawl results.</td></tr>';renderAllModules();}
function loadSaved(){try{const x=JSON.parse(localStorage.getItem('GEORUSH_LAST_CRAWL')||'null');if(x&&Array.isArray(x.results))LAST_CRAWL=x;}catch{}}
async function runCrawl(){const url=$('#site')?.value.trim();if(!url){$('#msg').textContent='Enter a website URL.';return;}$('#status').textContent='RUNNING';$('#msg').textContent='Crawling...';$('#runAudit').disabled=true;try{const data=await api('/api/crawl',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,max_pages:25})});renderResults(data);$('#msg').textContent='Audit complete.';}catch(e){$('#status').textContent='API OFFLINE';$('#msg').textContent='Crawl failed: '+(e.message||'start the Python API.');}finally{$('#runAudit').disabled=false;}}
async function performSearch(){const q=$('#globalSearch')?.value.trim().toLowerCase();if(!q){$('#msg').textContent='Enter a search term.';return;}$('#searchBtn').disabled=true;$('#msg').textContent='Searching...';let results=[];let online=false;try{const d=await api('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,limit:50})});results=d.results||[];online=true;}catch{results=(LAST_CRAWL?.results||[]).filter(x=>`${x.url} ${x.title||''} ${x.description||''} ${x.h1||''} ${(x.issues||[]).join(' ')}`.toLowerCase().includes(q));}$('#rows').innerHTML=results.length?results.map(rowHtml).join(''):'<tr><td colspan="6">No matching results.</td></tr>';$('#msg').textContent=online?`${results.length} result(s) found.`:`${results.length} offline result(s) found.`;$('#searchBtn').disabled=false;showPage('dashboard');}

function metric(label,value,sub=''){return `<div class="metric"><small>${escapeHtml(label)}</small><strong>${escapeHtml(value)}</strong><span>${escapeHtml(sub)}</span></div>`;}
function pages(){return LAST_CRAWL?.results||[];}
function issueSeverity(issue){if(/HTTP_ERROR|CRAWL_ERROR|BROKEN/i.test(issue))return'Critical';if(/MISSING|DUPLICATE|MULTIPLE|TOO_LONG|THIN/i.test(issue))return'Warning';return'Info';}
function renderKeywords(){const el=$('#keywordRows');if(!el)return;$('#keywordSource').textContent='GSC REQUIRED';$('#keywordMetrics').innerHTML=metric('Queries','—','Connect GSC')+metric('Clicks','—','Connect GSC')+metric('Impressions','—','Connect GSC')+metric('Avg. Position','—','Connect GSC');el.innerHTML='<tr><td colspan="7">Real keyword queries are not available until Google Search Console is connected. Your crawl data is ready for GSC mapping.</td></tr>';}
function renderRankings(){const ps=pages();$('#rankingMetrics').innerHTML=metric('Pages',ps.length,ps.length?'Crawled pages':'Run audit')+metric('HTTP 200',ps.filter(p=>p.status_code===200).length,'Healthy responses')+metric('Pages with issues',ps.filter(p=>(p.issues||[]).length).length,'Needs attention')+metric('Best content depth',ps.length?Math.max(...ps.map(p=>p.word_count||0)):'—','Words');$('#rankingRows').innerHTML=ps.length?ps.slice().sort((a,b)=>(b.word_count||0)-(a.word_count||0)).map(p=>`<tr><td>${escapeHtml(p.url)}</td><td>${(p.issues||[]).length?'Needs optimization':'Healthy'}</td><td>${p.word_count||0}</td><td>${p.h1_count??(p.h1?1:0)}</td><td>${escapeHtml((p.issues||[]).join(', ')||'None')}</td></tr>`).join(''):'<tr><td colspan="5">Run an audit first.</td></tr>';}
async function inspectCompetitor(){const url=$('#competitorUrl').value.trim();if(!url)return;$('#inspectCompetitor').disabled=true;$('#competitorResult').innerHTML='<div class="empty-state">Inspecting competitor...</div>';try{const d=await api('/api/competitor/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});if(d.error)throw new Error(d.error);const s=d.signals||{};$('#competitorResult').innerHTML=`<div class="compare-card"><h3>${escapeHtml(d.final_url||d.url)}</h3><div class="metric-grid">${metric('HTTP Status',d.status,'Response')}${metric('Load',`${d.response_time_ms} ms`,'Response time')}${metric('Words',s.word_count||0,'Page content')}${metric('H1 Count',s.h1_count||0,'Headings')}${metric('Internal Links',s.internal_links||0,'Discovered')}${metric('External Links',s.external_links||0,'Discovered')}</div><p><b>Title:</b> ${escapeHtml(s.title||'—')}</p><p><b>Description:</b> ${escapeHtml(s.description||'—')}</p></div>`;}catch(e){$('#competitorResult').innerHTML=`<div class="empty-state">Competitor inspection failed: ${escapeHtml(e.message||'Unknown error')}</div>`;}finally{$('#inspectCompetitor').disabled=false;}}
function renderAudit(){const ps=pages();const score=LAST_CRAWL?.seo_score||{};$('#auditGrade').textContent=score.grade?`${score.grade} • ${score.total}`:'NO AUDIT';const counts={};ps.forEach(p=>(p.issues||[]).forEach(i=>counts[i]=(counts[i]||0)+1));$('#auditMetrics').innerHTML=metric('SEO Score',score.total??'—',score.grade||'Run audit')+metric('Pages',ps.length,'Crawled')+metric('Issue types',Object.keys(counts).length,'Unique checks')+metric('Total issues',Object.values(counts).reduce((a,b)=>a+b,0),'Across pages');$('#issueSummary').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([i,n])=>`<div class="issue-card"><span class="severity ${issueSeverity(i).toLowerCase()}">${issueSeverity(i)}</span><b>${escapeHtml(i)}</b><strong>${n}</strong><small>page${n===1?'':'s'}</small></div>`).join('')||'<div class="empty-state">No issues detected.</div>';$('#auditRows').innerHTML=ps.length?ps.map(p=>`<tr><td>${escapeHtml(p.url)}</td><td>${p.status_code??0}</td><td>${p.issues?.length?issueSeverity(p.issues[0]):'Healthy'}</td><td>${escapeHtml((p.issues||[]).join(', ')||'None')}</td><td>${p.response_time_ms??0} ms</td></tr>`).join(''):'<tr><td colspan="5">Run an audit first.</td></tr>';}
function renderContent(){const ps=pages();const thin=ps.filter(p=>(p.word_count||0)<300).length;const missingDesc=ps.filter(p=>!p.description).length;const multiH1=ps.filter(p=>(p.h1_count||0)>1).length;$('#contentMetrics').innerHTML=metric('Pages',ps.length,'Crawled')+metric('Thin pages',thin,'Under 300 words')+metric('Missing descriptions',missingDesc,'Meta description')+metric('Multiple H1',multiH1,'Heading structure');$('#contentRows').innerHTML=ps.length?ps.map(p=>`<tr><td>${escapeHtml(p.url)}</td><td>${escapeHtml(p.title||'—')}</td><td>${p.word_count||0}</td><td>${p.description?escapeHtml(p.description.slice(0,100)):'Missing'}</td><td>${p.h1_count??(p.h1?1:0)}</td><td>${escapeHtml((p.issues||[]).filter(i=>/TITLE|DESCRIPTION|H1|THIN_CONTENT/i.test(i)).join(', ')||'None')}</td></tr>`).join(''):'<tr><td colspan="6">Run an audit first.</td></tr>';}
function renderBacklinks(){const ps=pages();const internal=ps.reduce((n,p)=>n+(p.internal_links||0),0),external=ps.reduce((n,p)=>n+(p.external_links||0),0);$('#backlinkMetrics').innerHTML=metric('Pages',ps.length,'Crawled')+metric('Internal links',internal,'Discovered')+metric('External links',external,'Discovered')+metric('Avg internal/page',ps.length?(internal/ps.length).toFixed(1):'—','Crawl signal');$('#backlinkRows').innerHTML=ps.length?ps.map(p=>`<tr><td>${escapeHtml(p.url)}</td><td>${p.internal_links??0}</td><td>${p.external_links??0}</td><td>${(p.internal_links||0)>0?'Connected':'Orphan-like signal'}</td></tr>`).join(''):'<tr><td colspan="4">Run an audit first.</td></tr>';}
function renderAnalytics(){const ps=pages();const avg=ps.length?Math.round(ps.reduce((n,p)=>n+(p.response_time_ms||0),0)/ps.length):0;$('#analyticsMetrics').innerHTML=metric('Pages crawled',ps.length,'Crawler')+metric('Avg load',avg?`${avg} ms`:'—','Response time')+metric('HTTP 200',ps.filter(p=>p.status_code===200).length,'Healthy responses')+metric('Total words',ps.reduce((n,p)=>n+(p.word_count||0),0).toLocaleString(),'Crawled content');$('#analyticsCrawlerStatus').textContent=ps.length?`${ps.length} pages loaded from latest audit`:'No audit loaded';}
function renderCompetitor(){if(!$('#competitorUrl').value && $('#site').value)$('#competitorUrl').value='';}
function renderAllModules(){renderKeywords();renderRankings();renderAudit();renderContent();renderBacklinks();renderAnalytics();renderCompetitor();}
function renderModule(page){if(page==='keywords')renderKeywords();if(page==='rankings')renderRankings();if(page==='audit')renderAudit();if(page==='content')renderContent();if(page==='backlinks')renderBacklinks();if(page==='analytics')renderAnalytics();}
window.GEORUSH={showPage,runCrawl,performSearch};
document.addEventListener('DOMContentLoaded',()=>{loadSaved();initNavigation();checkAPI();if(LAST_CRAWL)renderResults(LAST_CRAWL);$('#runAudit')?.addEventListener('click',runCrawl);$('#searchBtn')?.addEventListener('click',performSearch);$('#globalSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')performSearch();});$('#inspectCompetitor')?.addEventListener('click',inspectCompetitor);});
